DROP SCHEMA IF EXISTS cooplan CASCADE;

CREATE SCHEMA IF NOT EXISTS cooplan;

CREATE TABLE IF NOT EXISTS cooplan.users (
    id BIGSERIAL PRIMARY KEY,
    username TEXT UNIQUE NOT NULL,
    password TEXT NOT NULL
);
